version: "3"

includes:
  mise: tasks/MiseTasks.yml
  sh: tasks/ShellTasks.yml
  yml: tasks/YamlTasks.yml
  json: tasks/JsonTasks.yml
  md: tasks/MarkdownTasks.yml
  gh: tasks/GitHubTasks.yml

tasks:
  default:
    cmds:
      - task: list
      - task: mise:versions

  list:
    desc: List all tasks
    cmd: task --list

  setup:
    desc: "Setup project"
    cmds:
      - task: mise:setup

  check:
    desc: "Check"
    deps:
      - sh:check
      - yml:check
      - json:fmt
      - md:check
      - gh:check
