name: 'Commit and Push'
description: 'Commits and pushes changes if any exist'

inputs:
  commit-message:
    description: 'Commit message'
    required: false
    default: 'Auto commit'

  github-token:
    description: 'GitHub token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Commit and Push
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
          git add -A
          git commit -m "$COMMIT_MESSAGE"
          git push origin HEAD:$BRANCH_NAME
        else
          echo "No changes to commit."
        fi
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        COMMIT_MESSAGE: ${{ inputs.commit-message }}
        BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
