name: Check Shell Scripts

on:
  push:
    paths:
      - 'src/*.sh'
      - '.github/workflows/check-shell.yml'
  pull_request:
    paths:
      - 'src/*.sh'
      - '.github/workflows/check-shell.yml'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Install Task
      uses: arduino/setup-task@v2

    - name: Install mise and setup
      uses: jdx/mise-action@v3
      with:
        install: true
        cache: true
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Format
      run: task sh:fmt

    - name: Commit and Push
      uses: ./.github/actions/commit-and-push
      with:
        commit-message: "Auto fix code by `task sh:fmt`"
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Check
      run: task sh:check
