name: Dependabot Auto Approve and Merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  approve-and-merge:
    runs-on: ubuntu-latest

    if: github.event.pull_request.user.login == 'dependabot[bot]'

    steps:
        - name: Dependabot Auto Approve and Merge
          uses: ./.github/actions/auto-approve-and-merge
          with:
            pr-url: ${{ github.event.pull_request.html_url }}
            github-token: ${{ secrets.GITHUB_TOKEN }}
